const express=require('express');const crypto=require('crypto');const path=require('path');const {Pool}=require('pg');const app=express();const PORT=process.env.PORT||10000;const publicDir=path.join(__dirname,'public');app.use(express.json({limit:'300kb'}));app.use(express.urlencoded({extended:true}));
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:5}):null;
const fields=['title','organization','department','employment_type','state','location','total_vacancies','qualification','age_limit','salary','application_fee','start_date','last_date','selection_process','exam_date','description','eligibility','required_documents','how_to_apply','official_website_url','notification_pdf_url','apply_online_url','important_links','category','tags','status'];
const col=f=>`"${f}"`;
async function initDb(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS jobs (id BIGSERIAL PRIMARY KEY,slug TEXT UNIQUE NOT NULL,title TEXT NOT NULL,organization TEXT NOT NULL,department TEXT,employment_type TEXT,state TEXT,location TEXT,total_vacancies TEXT,qualification TEXT,age_limit TEXT,salary TEXT,application_fee TEXT,start_date TEXT,last_date TEXT,selection_process TEXT,exam_date TEXT,description TEXT,eligibility TEXT,required_documents TEXT,how_to_apply TEXT,official_website_url TEXT,notification_pdf_url TEXT,apply_online_url TEXT,important_links TEXT,category TEXT,tags TEXT,status TEXT NOT NULL DEFAULT 'Draft',created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());CREATE INDEX IF NOT EXISTS jobs_status_idx ON jobs(status);CREATE INDEX IF NOT EXISTS jobs_last_date_idx ON jobs(last_date);`);const n=await pool.query('SELECT COUNT(*)::int AS n FROM jobs');if(n.rows[0].n===0)await pool.query(`INSERT INTO jobs(slug,title,organization,department,employment_type,state,location,total_vacancies,qualification,age_limit,salary,application_fee,description,eligibility,required_documents,how_to_apply,official_website_url,category,tags,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)`,['demo-job-replace-with-verified-notification','DEMO — Replace with verified recruitment notification','DEMO ORGANIZATION','Demo Department','Government','Assam','Demo Location','1','12th Pass','Not specified in notification','Not specified in notification','Not specified in notification','Demo record for testing only. Replace with a verified official recruitment notification before publishing.','Not specified in notification','Not specified in notification','Not specified in notification','https://example.gov.in','12th Pass','demo,testing','Draft']);}
async function allJobs(){if(pool){const r=await pool.query('SELECT * FROM jobs ORDER BY created_at DESC');return r.rows}return []}async function oneJob(id){const r=await pool.query('SELECT * FROM jobs WHERE id=$1',[id]);return r.rows[0]}
function sign(v){return crypto.createHmac('sha256',process.env.ADMIN_SESSION_SECRET||'change-me').update(v).digest('hex')}function token(){const t=Date.now().toString();return Buffer.from(t+'|'+sign(t)).toString('base64url')}function isAdmin(req){try{const c=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('admin_session='));if(!c)return false;const [t,s]=Buffer.from(c.split('=')[1],'base64url').toString().split('|');return !!t&&!!s&&Date.now()-Number(t)<86400000&&crypto.timingSafeEqual(Buffer.from(s),Buffer.from(sign(t)))}catch{return false}}function auth(req,res,next){if(!isAdmin(req))return res.status(401).json({error:'Admin login required'});next()}
app.get('/api/health',async(q,s)=>{try{if(pool)await pool.query('SELECT 1');s.json({ok:true,service:'ASHINUR CAREER',database:!!pool})}catch(e){s.status(503).json({ok:false,database:false})}});
app.post('/api/admin/login',(q,s)=>{if(String(q.body?.username||'')!==process.env.ADMIN_USERNAME||String(q.body?.password||'')!==process.env.ADMIN_PASSWORD)return s.status(401).json({error:'Invalid admin credentials'});s.setHeader('Set-Cookie',`admin_session=${token()}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=86400`);s.json({ok:true})});app.post('/api/admin/logout',(q,s)=>{s.setHeader('Set-Cookie','admin_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0');s.json({ok:true})});app.get('/api/admin/me',auth,(q,s)=>s.json({ok:true,username:process.env.ADMIN_USERNAME}));
app.get('/api/jobs',async(q,s)=>{try{const rows=await allJobs(),search=String(q.query.q||'').toLowerCase(),qual=String(q.query.qualification||'').toLowerCase(),state=String(q.query.state||'').toLowerCase(),category=String(q.query.category||'').toLowerCase();s.json({jobs:rows.filter(j=>j.status==='Published'&&(!search||[j.title,j.organization,j.qualification,j.location,j.tags,j.category].join(' ').toLowerCase().includes(search))&&(!qual||qual==='all qualifications'||String(j.qualification||'').toLowerCase().includes(qual))&&(!state||state==='all states'||String(j.state||'').toLowerCase().includes(state))&&(!category||category==='all categories'||String(j.category||'').toLowerCase().includes(category)))})}catch(e){s.status(500).json({error:'Unable to load jobs'})}});
app.get('/api/jobs/:slug',async(q,s)=>{try{const r=await pool.query('SELECT * FROM jobs WHERE slug=$1 AND status=$2',[q.params.slug,'Published']);if(!r.rows[0])return s.status(404).json({error:'Job not found'});s.json({job:r.rows[0]})}catch(e){s.status(500).json({error:'Unable to load job'})}});
app.get('/api/admin/stats',auth,async(q,s)=>{const r=await pool.query("SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='Published')::int published,COUNT(*) FILTER(WHERE status='Draft')::int draft,COUNT(*) FILTER(WHERE status='Expired')::int expired FROM jobs");s.json(r.rows[0])});app.get('/api/admin/jobs',auth,async(q,s)=>s.json({jobs:await allJobs()}));
app.post('/api/admin/job',auth,async(q,s)=>{try{const b=q.body||{};if(!b.title||!b.organization)return s.status(400).json({error:'title and organization are required'});let slug=String(b.slug||b.title).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,140);const exists=await pool.query('SELECT 1 FROM jobs WHERE slug=$1',[slug]);if(exists.rowCount)slug+='-'+Date.now();const vals=fields.map(f=>b[f]??(f==='status'?'Draft':null));const cols=['slug',...fields].map(col).join(',');const r=await pool.query(`INSERT INTO jobs(${cols}) VALUES(${vals.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING *`,[slug,...vals]);s.status(201).json({job:r.rows[0]})}catch(e){s.status(500).json({error:'Unable to create job'})}});
app.put('/api/admin/job/:id',auth,async(q,s)=>{try{const sets=fields.filter(f=>Object.hasOwn(q.body||{},f));if(!sets.length)return s.status(400).json({error:'No fields to update'});const vals=sets.map(f=>q.body[f]);const r=await pool.query(`UPDATE jobs SET ${sets.map((f,i)=>`${col(f)}=$${i+1}`).join(',')},updated_at=NOW() WHERE id=$${sets.length+1} RETURNING *`,[...vals,q.params.id]);if(!r.rows[0])return s.status(404).json({error:'Job not found'});s.json({job:r.rows[0]})}catch(e){s.status(500).json({error:'Unable to update job'})}});
app.delete('/api/admin/job/:id',auth,async(q,s)=>{const r=await pool.query('DELETE FROM jobs WHERE id=$1 RETURNING id',[q.params.id]);if(!r.rows[0])return s.status(404).json({error:'Job not found'});s.json({ok:true})});app.post('/api/admin/import',auth,(q,s)=>{const text=String(q.body?.text||'').trim();if(!text)return s.status(400).json({error:'Paste notification text.'});s.json({extracted:{description:text},workflow:'Draft only — review before publishing.'})});
app.use(express.static(publicDir));app.get('/jobs/:slug',(q,s)=>s.sendFile(path.join(publicDir,'jobs','index.html')));app.get('/admin',(q,s)=>s.sendFile(path.join(publicDir,'admin.html')));app.get('/admin-import',(q,s)=>s.sendFile(path.join(publicDir,'admin-import.html')));app.use((q,s)=>s.sendFile(path.join(publicDir,'index.html')));
initDb().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`ASHINUR CAREER listening on ${PORT}`))).catch(e=>{console.error('DB init failed',e);process.exit(1)});